FROM golang:1 AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ENV CGO_ENABLED=0
RUN go build -o /sbapi -ldflags "-w -s" ./sbapi

FROM alpine
RUN apk add --no-cache ca-certificates
RUN adduser -D thorium-salty
COPY --from=builder /sbapi /usr/bin/sbapi
USER thorium-salty
ENTRYPOINT ["/usr/bin/sbapi"]
