FROM golang:1 AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ENV CGO_ENABLED=0
RUN go build -o /twchat -ldflags "-w -s" ./twchat

FROM alpine
RUN apk add --no-cache ca-certificates
RUN adduser -D thorium-twitch
COPY --from=builder /twchat /usr/bin/twchat
USER thorium-twitch
ENTRYPOINT ["/usr/bin/twchat"]
